### ISSUE TITLE
DKIM not valid when using multipart/alternative

### ISSUE THREAD

**Issue by TheSquad** [gen-smtp/gen_smtp#83] opened 2015-03-22 16:17 UTC
Hi,

I would like to use multipart/alternative so I can pass SpamAssassin spam's check.

Unfortunately it seems that when using multipart/alternive, instead of text/html, the DKIM is not valid for the receiver... according to mail-tester.com

``` Erlang
sendEncryptedEmail([], _,  _, _, _) ->
    ok;
sendEncryptedEmail([R|Tail], Subject, HtmlBody, PlainBody, PrivKey) ->
    DKIMOptions = [
                   {s, <<"key1">>},
                   {d, <<"MyDomain.net">>},
                   {private_key, {pem_plain, PrivKey}}
                  ],
    Row = re:replace(R, "\\s+", "", [global, {return, list}]),
    case Row of
        [] ->
            sendEncryptedEmail(Tail, Subject, HtmlBody, PlainBody, PrivKey);
        _ ->
            SignedMailBody = case PlainBody of
                                 none ->
                                     mimemail:encode(
                                       {<<"text">>, <<"html">>,
                                        [
                                         {<<"Subject">>, tools:binarize(Subject)},
                                         {<<"From">>, <<"MyDomain <no-reply@MyDomain.net>">>},
                                         {<<"To">>, tools:binarize(Row)}
                                        ],
                                        [],
                                        HtmlBody
                                       },
                                       [
                                        {dkim, DKIMOptions}
                                       ]
                                      );
                                 _ ->
                                     mimemail:encode(
                                       {<<"multipart">>,<<"alternative">>,
                                        [{<<"From">>, <<"MyDomain <no-reply@MyDomain.net>">>},
                                         {<<"To">>, tools:binarize(Row)},
                                         {<<"Subject">>, tools:binarize(Subject)}],
                                        [],
                                        [{<<"text">>, <<"plain">>,
                                          [{<<"Content-Type">>, <<"text/plain;charset=utf-8">>},
                                           {<<"Content-Disposition">>, <<"inline">>}],
                                          [],
                                          PlainBody},
                                         {<<"text">>, <<"html">>,
                                          [{<<"Content-Type">>, <<"text/html;charset=utf-8">>},
                                           {<<"Content-Disposition">>, <<"inline">>}],
                                          [],
                                          HtmlBody}]},
                                       [
                                        {dkim, DKIMOptions}
                                       ]
                                      )
                             end,
            P = gen_smtp_client:send_blocking({"no-reply@MyDomain.net", [Row], SignedMailBody}, [{relay, localhost}]),
            sendEncryptedEmail(Tail, Subject, HtmlBody, PlainBody, PrivKey)
    end.
```

The result are : 

```
mailing:sendEncryptedEmail(["web-XXXXXX@mail-tester.com"], "Hello World", tools:readFile("/var/www/newsletter_11_15_14/emailing.txt"), tools:readFile("/var/www/newsletter_11_15_14/emailing_txt.txt"), tools:readFile("/home/user/private-key.pem")).

The email received is flagged with wrong DKIM.

mailing:sendEncryptedEmail(["web-XXXXXX@mail-tester.com"], "Hello World", tools:readFile("/var/www/newsletter_11_15_14/emailing.txt"), none, tools:readFile("/home/user/private-key.pem")).

The email received is flagged with good DKIM
```

Any idea why ? Thanks !

**Comment by mworrell** [comment] 2019-07-18 16:27
@aran do you recognize this problem?

**Comment by mworrell** [comment] 2019-07-18 16:27
@arjan do you recognize this problem?

**Comment by seriyps** [comment] 2019-07-18 19:12
I can try to look at it since I contributed DKIM implementation

**Comment by mworrell** [comment] 2019-07-18 20:07
@seriyps thanks, maybe we can create some test sets and see if the error can be reproduced.

**Comment by seriyps** [comment] 2019-07-18 22:27
I tried to reproduce this, but in my case multipart version worked well. I tried following code:

```erlang
main({ToName, ToDomain}, PrivKey, Password) ->
    ToAddr= <<ToName/binary, "@", ToDomain/binary>>,
    DKIMOptions = [
                   {s, <<"dkim-1">>},
                   {d, <<"dropmail.me">>},
                   {private_key, {pem_encrypted, PrivKey, Password}}
                  ],
    PlainBody = <<"Hello world">>,
    HtmlBody = <<"<html><body><p>Hello, html world</p></body></html>">>,
    SignedBody =
        mimemail:encode(
          {<<"multipart">>,<<"alternative">>,
           [{<<"From">>, <<"MyDomain <no-reply@dropmail.me>">>},
            {<<"To">>, ToAddr},
            {<<"Subject">>, <<"Hello!">>}],
           [],
           [{<<"text">>, <<"plain">>,
             [{<<"Content-Type">>, <<"text/plain;charset=utf-8">>},
              {<<"Content-Disposition">>, <<"inline">>}],
             [],
             PlainBody},
            {<<"text">>, <<"html">>,
             [{<<"Content-Type">>, <<"text/html;charset=utf-8">>},
              {<<"Content-Disposition">>, <<"inline">>}],
             [],
             HtmlBody}]},
          [
           {dkim, DKIMOptions}
          ]
         ),
    io:format("~p~n", [SignedBody]),
    gen_smtp_client:send_blocking({<<"no-reply@dropmail.me">>, [ToAddr], SignedBody},
                                  [{relay, binary_to_list(ToDomain)},
                                   {trace_fun, fun io:format/2}]).
```

```
> {ok, B} = file:read_file("deploy/keys/*****-private.pem").
{ok,<<"-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: DES-EDE3-CBC,213C7D02AA80B91B\n\nTvCrYwNthw7F"...>>}                                                                                                  
2> smtp_test:main({<<"test-rovmu">>, <<"mail-tester.com">>}, B, "*****").
<<"DKIM-Signature: s=dkim-1;\r\n\t h=from:to:subject:date;\r\n\t d=dropmail.me;\r\n\t c=relaxed/simple;\r\n\t bh=PlXXea/tTNVQxJSnJyeKYeBc+P7HO+1mNLB/9Mauz7s=;\r\n\t a=rsa-sha256;\r\n\t v=1;\r\n\t b=Do0dSUwWbnXwrRSxVHMq9WpBqVlHIC9FVgE0GujypGZLjuao+RK5y+NMqXZjwpS7QYZwEQiVPKF1mR5q3/E9RKSA0JUEf8woURXJjdn/1XZlon1+/r1mhnpxIRCGnhnkuW6/cfQWbLESgMWb3MypN3bCfkEzIKINCAfHktmAc90=\r\nFrom: MyDomain <no-reply@dropmail.me>\r\nTo: test-rovmu@mail-tester.com\r\nSubject: Hello!\r\nContent-Type: multipart/alternative;\r\n\tboundary=\"_=155u5z3c5419203w1q3m1q3s2u513k5p=_\"\r\nMIME-Version: 1.0\r\nDate: Fri, 19 Jul 2019 00:18:19 +0200\r\nMessage-ID: <a366c68c19d2d67b253289507a6102ee@seriy-laptop>\r\n\r\n\r\n--_=155u5z3c5419203w1q3m1q3s2u513k5p=_\r\nContent-Type: text/plain;\r\n\tcharset=utf-8\r\nContent-Disposition: inline\r\n\r\nHello world\r\n--_=155u5z3c5419203w1q3m1q3s2u513k5p=_\r\nContent-Type: text/html;\r\n\tcharset=utf-8\r\nContent-Disposition: inline\r\n\r\n<html><body><p>Hello, html world</p></body></html>\r\n--_=155u5z3c5419203w1q3m1q3s2u513k5p=_--\r\n">>                                                               
MX records for mail-tester.com are [{1,"mail-tester.com"}]
connected to mail-tester.com; banner was  mail-tester.com ESMTP Postfix (Ubuntu)

Extensions are [{<<"PIPELINING">>,true},
                {<<"SIZE">>,<<"10240000">>},
                {<<"VRFY">>,true},
                {<<"ETRN">>,true},
                {<<"STARTTLS">>,true},
                {<<"ENHANCEDSTATUSCODES">>,true},
                {<<"8BITMIME">>,true}]
Starting TLS
TLS started
Extensions are [{<<"PIPELINING">>,true},
                {<<"SIZE">>,<<"10240000">>},
                {<<"VRFY">>,true},
                {<<"ETRN">>,true},
                {<<"ENHANCEDSTATUSCODES">>,true},
                {<<"8BITMIME">>,true}]
Authentication status is false
<<"2.0.0 Ok: queued as 02D299F8A1\r\n">>
```

And here is the test result: https://www.mail-tester.com/test-rovmu:

![screenshot](https://user-images.githubusercontent.com/422014/61496230-df30b300-a9bb-11e9-9942-1b5416c30cd3.png)

**Comment by mworrell** [comment] 2019-07-19 07:15
Thanks for testing!

The problem might have been fixed in the last couple of years.
Closing this issue.

**Closed by mworrell** 2019-07-19 07:15 UTC
Labels: waits for input
