### ISSUE TITLE
server_name_indication error

### ISSUE THREAD

**Issue by p-g-krish** [gen-smtp/gen_smtp#131] opened 2017-07-14 13:52 UTC
I Tested mail sending program based on gen_smtp . When i ran the program , Its returns the following error 

> 
> 
> {ok,<0.74.0>}
> ** exception error: {error,retries_exceeded,
>                         {network_failure,"74.125.68.109",
>                             {error,
>                                 {options,{{server_name_indication,"74.125.68.109"}}}}}}

**Comment by Vagabond** [comment] 2017-07-14 16:08
How were you calling the client? (please obfuscate username/password).

**Comment by Vagabond** [comment] 2017-07-14 16:19
My guess is that that server is hosting several SMTP domains and we need to pass the 'server name indication' over TLS to it.

**Comment by p-g-krish** [comment] 2017-07-15 05:02
-module(mail).
-export([start/0]).

start() ->
   gen_smtp_client:send({"sender@gmail.com", ["receiver@gmail.com"], "Subject: testing"},

   [{relay, "smtp.gmail.com"}, {ssl, true}, {username, "sender@gmail.com"},
      {password, "mypass"}]).

**Comment by comtihon** [comment] 2017-07-23 12:32
Hi! I guess I have the same problem.
I've tried this:
```
1> application:ensure_all_started(ssl).                                                                                              
{ok,[crypto,asn1,public_key,ssl]} ``
2> gen_smtp_client:send_blocking({From, [To], <<"hello there">>}, [{relay, "smtp.gmail.com"}, {username, From}, {password, Pass}, {ssl, true}, {auth, always}]).
```
The strange thing is - everything is fine on my laptop (command works).
But on a server, hosted with Scaleway it is not working. I have got an error `{error,retries_exceeded,                                                                                                             
       {network_failure,"smtp.gmail.com",{error,timeout}}}`

**Comment by mworrell** [comment] 2017-07-24 09:02
Try to connect manually from the command line on your server (using telnet).

```
$ telnet smtp.gmail.com 25
Trying 2a00:1450:4013:c04::6d...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP x15sm1815610edk.65 - gsmtp
QUIT
221 2.0.0 closing connection x15sm1815610edk.65 - gsmtp
Connection closed by foreign host.
```

**Comment by p-g-krish** [comment] 2017-07-24 09:36
@mworrell  , I checked with Telnet and smtp. Its returns positive similar to yours. But the mail was not sending

**Comment by comtihon** [comment] 2017-07-25 17:39
@mworrell 
thanks for telnet idea. It turned out my hoster blocks smtp by default.
So it is not my issue any more.

**Comment by mworrell** [comment] 2019-07-18 15:50
@p-g-krish did you get this working

**Comment by mworrell** [comment] 2019-07-18 15:53
@p-g-krish We are regularly sending email to gmail addresses and not encountering this error. Did you use another recipient domain than the one you showed?

**Comment by mworrell** [comment] 2020-03-09 11:13
Closing this issue due to inactivity.

**Comment by izinin** [comment] 2020-04-13 20:48
does not work at all , waste of time , so frustrated , switched to using python with erlang:execute_os_sync(binary_to_list(CMD))

```
execute_os_sync(Cmd) ->
    Port = erlang:open_port({spawn, Cmd}, [stream, use_stdio, exit_status, binary]),
    {ok, Data, Status} = wait(Port, []),
    case erlang:port_info(Port) of
        undefined -> ok;
        _ -> true = erlang:port_close(Port)
    end,
    {Data, Status}.
```
:(

**Comment by mworrell** [comment] 2020-04-13 22:29
@izinin are you reacting to this issue of gen_smtp? If there are any problems we would like to know them, as this library is in full use.

**Comment by izinin** [comment] 2020-04-14 13:48
@mworrell yes, i hit exactly the same problem as it is reported in this ticket , gen_smtp works well on my local computer but when i deployed it to cloud , it shows error `network_faillure` even i checked with telnet smtp.google is reachable  in the both SSL ports. Surprisingly `smtplib` from python works nicely with the same conditions. i had to revert my work because the error message gives no clue for me what could be wrong in gen_smtp , because the infrastructure setup allows sending email with python.
Regards,
Igor

**Comment by mworrell** [comment] 2020-04-14 16:08
Interesting, what version of OTP are you using?  Wondering if it is problem with the TLS ciphers.

We are using 18, 19, and 20 in production.

**Comment by seriyps** [comment] 2020-04-14 21:18
I have a service that receives ~50k emails and sends ~10k emails per-day from/to various email services over all the internet and it works quite smoothly since 2012.
It would be perfect if you'll provide some of your error messages/stacktraces that gen_smtp generates so we could help.
Spawning a new python interpreter might work, but it's definitely far from optimal solution, because of significant overhead.

**Comment by izinin** [comment] 2020-04-16 11:46
@seriyps you are right. This acceptable for me because i expect sending max 1000 mails daily. This solution worked well for a 1,5 M user base messenger project in user content moderation with Google Cloud Vision . I am just wondering why it is so complicated in use in contrast to python smtplib. Maybe it is over engineered for my purpose. i wish i had Erlang native reliable solution.
As for error , i got exactly the same error as it is described in the ticked.  I run Mongoose 3.3.0 on OTP 19

**Comment by mworrell** [comment] 2020-04-16 13:40
@izinin You get the `server_name_indication` error or some other error?  And if so, to what host are you connecting?

**Comment by izinin** [comment] 2020-04-16 17:48
yes. i used 0.15.0 Here was my rebar.config gen_smtp dependency entry : 

```
  % email sending support
  {eiconv, "1.0.0"},
  {gen_smtp, {git, "https://github.com/gen-smtp/gen_smtp.git", {tag, "0.15.0"}}},

```
i tried Gmail with the `smtp.gmail.com` 

```erlang
handle_info({send_email, {To, Body}}, State) ->
    Opts = ejabberd_config:get_local_option(email_send, ?HOST),
	SMTP_SRV = proplists:get_value(smtp_srv, Opts),
	SMTP_USER = proplists:get_value(smtp_user, Opts),
	SMTP_PASSWD = proplists:get_value(smtp_passwd, Opts),
	From = proplists:get_value(mail_sender, Opts),
	Template = proplists:get_value(mail_header_template, Opts),
	EmailHeader = list_to_binary(lists:flatten(io_lib:format(Template, [From, To]))),
	Email = {From, [To], <<EmailHeader/binary,Body/binary>>},
	_Result = try gen_smtp_client:send_blocking(Email, [
			{relay, SMTP_SRV},
			{username, SMTP_USER},
			{password, SMTP_PASSWD},
			{ssl, true}
		])
	catch _:E ->
		lager:error("cannot send email: ~p",[E]),
		false
	end,
    {noreply, State};
```
it is working on my local computer but when i deployed to AWS linux box it gave me the error exactly as it is in this ticket but different IP.  

`{network_failure,"XXX", {error, {options,{{server_name_indication,"XXXX"}}}}}}`

i have checked SMTP SSL ports 465 and 587 are opened. I tried to use python smtplib and found it is working without problems , The ticket is opened long ago and the problem still persists, i found another bug report on gen_smtp with the same error message. so i reverted gen_smtp code from my implementation because i do not have time to debug gen_smtp lib.

Thank you for handling that case. 
Regards,
Igor

**Comment by mworrell** [comment] 2020-04-17 07:01
Do you have anything filled in for the relay and username/password options?

In the code I see that if the username/password options are present then library tries to authenticate. Even if they are set to the empty string or to `undefined`.

Which is a bit unexpected, but if you are not using the options, could you try without them?  If this is the cause then we can change the checks for the username/password so that the auth is only done if they are present and not empty (ie. `undefined`, `<<>>` or `""`).

**Comment by mworrell** [comment] 2020-04-17 07:03
Also, it seems that gmail needs SNI when connecting with an username/password. That is something to look into.

**Comment by mworrell** [comment] 2020-04-17 08:19
@izinin are you also using OTP 19 on production? (I am checking with OTP 19.3, but see below...)

@seriyps Do you have an AWS server to test this?

I am wondering where the error `{network_failure,"XXX", {error, {options,{{server_name_indication,"XXXX"}}}}}}` comes from.

The `{options, ...}` part looks like the result of `validate_options` in `ssl.erl`.  Except that the double `{{` before `server_name_indication` doesn't match the code I see in the OTP 19.3 version of `ssl.erl`.

```erlang
validate_option(server_name_indication, Value) when is_list(Value) ->
    Value;
validate_option(server_name_indication, disable) ->
    disable;
validate_option(server_name_indication, undefined) ->
    undefined;
...
validate_option(Opt, Value) ->
    throw({error, {options, {Opt, Value}}}).
```

I don't see how we can end up with an extra `{` before `Opt` here.


Other place in ssl.erl:

```erlang
new_ssl_options([{server_name_indication, Value} | Rest], #ssl_options{} = Opts, RecordCB) -> 
    new_ssl_options(Rest, Opts#ssl_options{server_name_indication = validate_option(server_name_indication, Value)}, RecordCB);
...
new_ssl_options([{Key, Value} | _Rest], #ssl_options{}, _) -> 
    throw({error, {options, {Key, Value}}}).
```

**Comment by mworrell** [comment] 2020-04-17 08:44
By the way, it seems the SNI option is added automatically, from the ssl manual:

> Specify the hostname to be used in TLS Server Name Indication extension. If not specified it will > default to the Host argument of connect/[3,4] unless it is of type inet:ipaddress().

**Comment by mworrell** [comment] 2020-04-17 12:23
Found it, including the double `{{`.

This is part of some SNI checking code that was only present in a couple of specific versions.

It was removed on Nov 29, 2017:

https://github.com/erlang/otp/commit/78a9a09af9216a2dea454f561e0774e67a15c361

And it was added on May 6, 2017:

https://github.com/erlang/otp/commit/e9b0dbb4a95dbc8e328f08d6df6654dcbe13db09#diff-79b520311347e34fac9cffbc4ea373f9R991

May I suggest to upgrade your Erlang version?

**Comment by mworrell** [comment] 2020-04-17 12:28
Conclusion: this is an issue that was resolved in later versions of OTP 19, and was caused by OTP adding the `server_name_indication` itself on ssl:connect calls in combination with a too strict check on validity of the passed hostname.

As upgrading to a new(er) minor version of OTP will resolve the problem, I close this issue.

**Closed by mworrell** 2020-04-17 12:28 UTC
Labels: waits for input
